services:
  apartment_sim:
    build: .
    platform: linux/amd64
    container_name: apartment_sim
    ports:
      - "6080:6080"
    environment:
      - DISPLAY=:99
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - GAZEBO_MODEL_PATH=/aws-robomaker-small-house-world/models:${GAZEBO_MODEL_PATH:-}
      - RCUTILS_COLORIZED_OUTPUT=1
    volumes:
      - ./src:/ros2_ws/src
      - ./worlds:/ros2_ws/worlds
      - ./scripts:/ros2_ws/scripts
      - ./logs:/ros2_ws/logs
    stdin_open: true
    tty: true